
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCRM_INFO_1", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZCRM_INFO_1_PortType {


    /**
     * 
     * @param ivtweg
     * @param ivkorg
     * @param imatnr
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZcrmProdusTt
     */
    @WebMethod(operationName = "ZcrmInfo1")
    @WebResult(name = "Einfo", targetNamespace = "")
    @RequestWrapper(localName = "ZcrmInfo1", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZcrmInfo1")
    @ResponseWrapper(localName = "ZcrmInfo1Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZcrmInfo1Response")
    public ZcrmProdusTt zcrmInfo1(
        @WebParam(name = "Imatnr", targetNamespace = "")
        String imatnr,
        @WebParam(name = "Ivkorg", targetNamespace = "")
        String ivkorg,
        @WebParam(name = "Ivtweg", targetNamespace = "")
        String ivtweg);

}
