
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCRM_PRODH", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZCRM_PRODH_PortType {


    /**
     * 
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZcrmProdhTt
     */
    @WebMethod(operationName = "ZcrmProdh")
    @WebResult(name = "Ierarhie", targetNamespace = "")
    @RequestWrapper(localName = "ZcrmProdh", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZcrmProdh")
    @ResponseWrapper(localName = "ZcrmProdhResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZcrmProdhResponse")
    public ZcrmProdhTt zcrmProdh();

}
