
package com.sap.document.sap.soap.functions.mc_style;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCRM_PRODH", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "/despec/ws_prodh/BN_ZCRM_PRODH.wsdl")
public class ZCRM_PRODH_Service
    extends Service
{

    private final static URL ZCRMPRODH_WSDL_LOCATION;
    private final static WebServiceException ZCRMPRODH_EXCEPTION;
    private final static QName ZCRMPRODH_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_PRODH");

    static {
        ZCRMPRODH_WSDL_LOCATION = com.sap.document.sap.soap.functions.mc_style.ZCRM_PRODH_Service.class.getResource("/despec/ws_prodh/BN_ZCRM_PRODH.wsdl");
        WebServiceException e = null;
        if (ZCRMPRODH_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/despec/ws_prodh/BN_ZCRM_PRODH.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ZCRMPRODH_EXCEPTION = e;
    }

    public ZCRM_PRODH_Service() {
        super(__getWsdlLocation(), ZCRMPRODH_QNAME);
    }

    public ZCRM_PRODH_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCRMPRODH_QNAME, features);
    }

    public ZCRM_PRODH_Service(URL wsdlLocation) {
        super(wsdlLocation, ZCRMPRODH_QNAME);
    }

    public ZCRM_PRODH_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCRMPRODH_QNAME, features);
    }

    public ZCRM_PRODH_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCRM_PRODH_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCRM_PRODH_PortType
     */
    @WebEndpoint(name = "ZCRM_PRODH")
    public ZCRM_PRODH_PortType getZCRMPRODH() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_PRODH"), ZCRM_PRODH_PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCRM_PRODH_PortType
     */
    @WebEndpoint(name = "ZCRM_PRODH")
    public ZCRM_PRODH_PortType getZCRMPRODH(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_PRODH"), ZCRM_PRODH_PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCRMPRODH_EXCEPTION!= null) {
            throw ZCRMPRODH_EXCEPTION;
        }
        return ZCRMPRODH_WSDL_LOCATION;
    }

}
